name: setup-haxe
description: "Sets up Haxe environment"

inputs:
  haxe:
    description: "Version of Haxe to install"
    required: true
    default: "4.3.4"

runs:
  using: "composite"
  steps:
    - name: Install Haxe
      uses: funkincrew/ci-haxe@v3.1.0
      with:
        haxe-version: ${{ inputs.haxe }}
