name: setup-haxe
description: "Sets up Haxe environment"

inputs:
  haxe:
    description: "Version of Haxe to install"
    required: true
    default: "4.3.4"

runs:
  using: "composite"
  steps:
    - name: Install git if missing
      shell: bash
      run: |
        if ! command -v git &> /dev/null; then
          echo "Installing git..."
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y git
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install git
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install git -y
          fi
        else
          echo "git is already installed"
        fi

    - name: Install Haxe
      uses: funkincrew/ci-haxe@v3.1.0
      with:
        haxe-version: ${{ inputs.haxe }}
