name: Build Game

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines to use
        default: "-DGITHUB_BUILD"
      save-artifact:
        type: boolean
        description: Save the build artifact to GitHub Actions
        default: true
      build-game:
        type: boolean
        description: "Should the game be built?"
        default: true  # Set to true if you want the game to build by default

jobs:
  build-game-on-host:
    strategy:
      matrix:
        include:
          - target: windows-latest
          - target: macos-latest
    runs-on: ${{ matrix.target }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set Git config for higher timeout
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999
          git config --global fetch.recurseSubmodules true
          git config --global submodule.fetchJobs 4

      - name: Setup Haxe
        uses: ./.github/actions/setup-haxe  # Only install Haxe

      - name: Run setup and build script
        run: |
          chmod +x ./art/install.sh
          ./art/install.sh "${{ matrix.target }}" "${{ github.event.inputs.build-defines }}" "${{ github.event.inputs.build-game }}" "true" # "true" indicates GitHub Actions environment

      - name: Save build artifact to GitHub Actions
        if: ${{ github.event.inputs.save-artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.target }}
          path: export/release/${{ matrix.target }}/bin/

  build-game-in-container:
    runs-on: ubuntu-latest
    container: ghcr.io/mackery6969/build-dependencies:latest
    strategy:
      matrix:
        include:
          - target: linux
          - target: html5
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run setup and build script
        run: |
          chmod +x ./art/install.sh
          ./art/install.sh "${{ matrix.target }}" "${{ github.event.inputs.build-defines }}" "${{ github.event.inputs.build-game }}" "true" # "true" indicates GitHub Actions environment

      - name: Save build artifact to GitHub Actions
        if: ${{ github.event.inputs.save-artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.target }}
          path: export/release/${{ matrix.target }}/bin/
