name: Create and publish Docker image

on:
  workflow_dispatch:
  push:
    paths:
      - "**/Dockerfile"
      - ".github/workflows/build-docker-image.yml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-layer-cache-${{ github.ref }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            docker-layer-cache-${{ github.ref }}-
            docker-layer-cache-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./build
          push: true
          tags: |
            ghcr.io/mackery6969/build-dependencies:latest
            ghcr.io/mackery6969/build-dependencies:${{ github.sha }}
          labels: |
            org.opencontainers.image.description=precooked haxe build-dependencies
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=${{ github.repository_owner }}/build-dependencies
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ github.sha }}
          cache-from: type=local,source=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
